CHG: Many more error checks. Improved clean-up on CTRL-C/kill.

diff --git a/bin/dcosima b/bin/dcosima
--- a/bin/dcosima
+++ b/bin/dcosima
@@ -7,8 +7,31 @@
 # Positive: number of available simulation slots
 
 # On exit, or if we hit ctrl-C, kill all your children
-trap "trap - SIGTERM && kill -- -$$" SIGTERM SIGINT EXIT 
+trap CleanUp SIGTERM SIGINT 
 
+CleanUp() {
+  echo " "
+  echo " "
+  echo "Received command to shut down gracefully..."
+  echo " "
+  P=$(jobs -p)
+  if [[ ${P} != "" ]]; then
+    echo "Killing all sub-processes..."
+    kill ${P}
+  fi
+  sleep 1
+  
+  echo "Killing all simulations..."
+  dcosima-kill -n=${LOCALDIR}
+  echo "Doing a final rsync..."
+  echo "Here: $(pwd)"
+  dcosima-rsync -i=0 -d=${HERE}/${LOCALDIR} -s=0
+  echo "Cleaning up remote directories..."
+  dcosima-clean -n=${LOCALDIR}
+  echo "DONE"
+  echo " "
+  exit 1
+}
 
 commandhelp() {
   echo ""
@@ -32,6 +55,7 @@ commandhelp() {
   echo "  dcosima -s=Crab.source -i=10 -p=CrabSim -z";
   echo "";
 }
+
 
 
 # Store command line as array
@@ -59,10 +83,14 @@ LOGGING="tee"
 DELAY="10"
 CFG=~/.dcosima.cfg
 
+
 # The number of already launched runs
 LAUNCHED=0
 # The run ID
 RUNID=${RANDOM}${RANDOM}${RANDOM}
+# Here we are
+HERE=$(pwd)
+
 
 # Overwrite default options with user options:
 for C in "${CMD[@]}"; do
@@ -230,6 +258,50 @@ fi
 
 # The md5 checksum of the configuration file to tell if it changed - initialize empty
 CFGMD5=""
+
+
+
+# Do a few more sanity checks
+
+# (1) Just one Run?
+RUNS=$(cat ${SOURCE} | grep "^Run" | wc -l)
+if [[ ${RUNS} -ne 1 ]]; then
+  echo " "
+  echo "ERROR: The source file must contain exactly one run and not ${RUNS}" | ${LOGGING}
+  exit 1
+fi
+
+# (2) Can we assemble all files?
+TMPDIR=$(mktemp -d /tmp/dcosima_tmp_dir.XXXXXXXXXX)
+dcosima-assemblefiles -s=${SOURCE} -d=${TMPDIR} > /dev/null
+if [ "$?" != "0" ]; then
+  rm -r ${TMPDIR}
+  echo " "
+  echo "ERROR: Failed to assemble files" | ${LOGGING}
+  exit 1
+fi
+
+# (3) Can we start the simulation?
+cd ${TMPDIR}
+OUT=$(timeout 15s cosima ${SOURCE})
+ERROR=$(echo ${OUT} | grep "Error")
+if [[ ${ERROR} != "" ]]; then
+  echo " "
+  echo "ERROR: Unable to perform a cosima test run. Error message:" | ${LOGGING}
+  echo " " 
+  echo "${OUT}" | ${LOGGING}
+  
+  rm -r ${TMPDIR}
+  
+  exit 1
+fi
+rm -r ${TMPDIR}
+
+# Done
+cd ${HERE}
+
+
+# Now start the all the simulations runs
 
 echo " "
 echo "Starting runs..." | ${LOGGING}
@@ -426,13 +498,13 @@ echo "DONE" >> ${RSYNCCFG}
 echo " * All processes lauched" | ${LOGGING}
 echo ""
 
-echo "Create a concatenation file"
-Base=`cat ${SOURCE} | grep -E "\.FileName|\.Filename|\.filename" | awk -F".FileName|.Filename|.filename" '{ print $2 }' | sed 's/^ *//g'`;
+echo "Create a concatenation file" | ${LOGGING}
+Base=`cat ${SOURCE} | grep -m 1 -E "\.FileName|\.Filename|\.filename" | awk -F".FileName|.Filename|.filename" '{ print $2 }' | sed 's/^ *//g'`;
 
 # Switch to the directory where all the data lands:
 cd ${LOCALDIR}
 
-echo "Creating concatenation file for simulation \"${Base}\""
+echo "Creating concatenation file for simulation \"${Base}\"" | ${LOGGING}
 ConcatFileName="${Base}.p1.sim"
 rm -f "${Base}.p1.sim*"
 
@@ -445,7 +517,7 @@ fi
 # Wait until the first such file is created
 while ( test ! -f ${FirstFileName} ); do
   sleep 1
-  echo "Waiting for the simulation file \"${FirstFileName}\" to appear ..."
+  echo "Waiting for the simulation file \"${FirstFileName}\" to appear ..." | ${LOGGING}
 done
 
 TMPFILE=`mktemp /tmp/dcosima.XXXXXXXXXX`
@@ -455,20 +527,20 @@ if [ ${ZIP} == "TRUE" ]; then
   while [ `gunzip -c ${FirstFileName} 2> /dev/null | wc -l | awk -F" " '{ print $1 }'` -le 100 ]; do
     # Remark: 2> /dev/null suppresses a "unexpected end of file" error message since the file is obviously not yet closed
     sleep 1;
-    echo "Waiting for first 100 lines to be written into the simulation file \"${FirstFileName}\" ..."
+    echo "Waiting for first 100 lines to be written into the simulation file \"${FirstFileName}\" ..." | ${LOGGING}
   done
   gunzip -c ${FirstFileName} 2> /dev/null | head -n 100 > ${TMPFILE}
 else
   while [ `wc -l ${FirstFileName} | awk -F" " '{ print $1 }'` -le 100 ]; do
     sleep 20;
-    echo "Waiting for first 100 lines to be written into the simulation file \"${FirstFileName}\" ..."
+    echo "Waiting for first 100 lines to be written into the simulation file \"${FirstFileName}\" ..." | ${LOGGING}
   done
   head -n 100 ${FirstFileName} > ${TMPFILE}
 fi
 
 
 # Create a concatenation file
-echo "Generating concatenation file..."
+echo "Generating concatenation file..." | ${LOGGING}
 echo "# Concatenation file generated by mcosima" >> ${ConcatFileName}
 
 
@@ -505,30 +577,30 @@ echo "Created concatenation file \"${ConcatFileName}\"" | ${LOGGING}
 
 
 echo " "
-echo "Waiting for rsync processes to finish..."
+echo "Waiting for rsync processes to finish..." | ${LOGGING}
 wait ${RSYNCPID}
 
-echo "All processes have finied and all data has been synced. Now deleting the remote data..."
+echo "All processes have finied and all data has been synced. Now deleting the remote data..." | ${LOGGING}
 for (( m=0; m<=$(( ${#MACHINES[*]} -1 )); m++ )); do
-  echo " * Deleting ${REMOTEMASTERDIR}/${LOCALDIR} on ${REMOTEHOST[$m]}"
+  echo " * Deleting ${REMOTEMASTERDIR}/${LOCALDIR} on ${REMOTEHOST[$m]}" | ${LOGGING}
 
   REMOTECOMMAND='COUNT=`grep -c ^directory ~/.dcosima.cfg`; if [ ${COUNT} -eq 1 ]; then grep ^directory ~/.dcosima.cfg; fi;'
   REMOTEMASTERDIR=$(ssh -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} 'bash -s' <<< ${REMOTECOMMAND} )
   if [ "$?" != "0" ]; then
-    echo "ERROR: Failed to read remote master directory"
+    echo "ERROR: Failed to read remote master directory" | ${LOGGING}
     continue
   fi
   REMOTEMASTERDIR=`echo ${REMOTEMASTERDIR} | awk '{ print $2 }'`
   if [ "${REMOTEMASTERDIR}" == "" ]; then
-    echo "ERROR: No remote master directory -- cannot delete anything!"
+    echo "ERROR: No remote master directory -- cannot delete anything!" | ${LOGGING}
     continue
   fi
  
   ssh -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} "rm -rf ${REMOTEMASTERDIR}/${LOCALDIR};"
 done
 
-echo " " 
+echo " " | ${LOGGING}
 echo "The simulations have finished!" | ${LOGGING}
-echo " "
+echo " " | ${LOGGING}
 
 exit 0;
