CHG: Only use the remote masterdir, if there is none quit CHG: Improve rsync ending conditions CHG: Improved initial sanity checks

diff --git a/bin/dcosima b/bin/dcosima
--- a/bin/dcosima
+++ b/bin/dcosima
@@ -119,20 +119,6 @@ fi
 # The md5 checksum of the configuration file to tell if it changed - initialize empty
 CFGMD5=""
 
-# Find the master simulation directory
-MASTERDIR=( `cat ${CFG} | grep "^directory" | gawk '{ print $2 }'` )
-if [[ "${MASTERDIR}" == "" ]]; then
-  MASTERDIR="dcosima"
-fi
-if [[ ${MASTERDIR} == /* ]]; then
-  echo "ERROR: The simulation directory can not be an absolute path! Using default path dcosima"
-  MASTERDIR="dcosima"
-fi
-if [[ ${MASTERDIR} == .* ]]; then
-  echo "ERROR: The simulation directory must sit in the users main directory! Using default path dcosima"
-  MASTERDIR="dcosima"
-fi
-
 echo " "
 echo "Starting runs:"
 LAUNCHED=0
@@ -157,17 +143,55 @@ while [[ ${LAUNCHED} -lt ${INSTANCES} ]]; do
     echo " "
     echo "Reading remote machines setup:"
     MACHINES=( `cat ${CFG} | grep "^machine" | gawk '{ print $2 }'` )
+    REMOTEUSER=( )
+    REMOTEHOST=( )
+    REMOTEPORT=( )
     for (( m=0; m<=$(( ${#MACHINES[*]} -1 )); m++ )); do
-      REMOTEUSER=`echo "${MACHINES[$m]}" | awk -F"@" '{ print $1 }'` 
-      REMOTEHOST=`echo "${MACHINES[$m]}" | awk -F"@" '{ print $2 }'  | awk -F":" '{ print $1 }'` 
-      REMOTEPORT=`echo "${MACHINES[$m]}" | awk -F":" '{ print $2 }'`
-      echo " * Found remote machine: ${MACHINES[$m]} (user: ${REMOTEUSER}, address: ${REMOTEHOST}, port: ${REMOTEPORT})"
+      REMOTEUSER[$m]=`echo "${MACHINES[$m]}" | awk -F"@" '{ print $1 }'` 
+      REMOTEHOST[$m]=`echo "${MACHINES[$m]}" | awk -F"@" '{ print $2 }'  | awk -F":" '{ print $1 }'` 
+      REMOTEPORT[$m]=`echo "${MACHINES[$m]}" | awk -F":" '{ print $2 }'`
+      echo " * Found remote machine: ${MACHINES[$m]} (user: ${REMOTEUSER[$m]}, address: ${REMOTEHOST[$m]}, port: ${REMOTEPORT[$m]})"
     done
     CFGMD5=`md5sum ${CFG}`
   fi
 
+  # Verify the machines:
+  AVAILABLEMACHINES=0
+  for (( m=0; m<=$(( ${#MACHINES[*]} -1 )); m++ )); do
+    REMOTECOMMAND='COUNT=`grep -c ^directory ~/.dcosima.cfg`; if [ ${COUNT} -eq 1 ]; then grep ^directory ~/.dcosima.cfg; fi;'
+    REMOTEMASTERDIR=$(ssh -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} 'bash -s' <<< ${REMOTECOMMAND} )
+    if [ "$?" != "0" ]; then
+      echo " "
+      echo "ERROR: Failed to read remote master directory on ${MACHINES[$m]} --- excluding remote machine"
+      MACHINES[$m]=""
+      continue
+    fi
+    REMOTEMASTERDIR=`echo ${REMOTEMASTERDIR} | awk '{ print $2 }'`
+    if [ "${REMOTEMASTERDIR}" == "" ]; then
+      echo " "
+      echo "ERROR: No remote master directory on ${MACHINES[$m]} --- excluding remote machine"
+      MACHINES[$m]=""
+      continue
+    fi
+    AVAILABLEMACHINES=$(( ${AVAILABLEMACHINES} + 1 ))
+  done
+  # If we have NO machines available, we quit...
+  if [ ${AVAILABLEMACHINES} -eq 0 ]; then
+    echo " "
+    echo "Unfortunately there are no machines available for simulations... Add a few more! Good bye..."
+    exit 0;
+  fi
+  
+  
   STARTED=0
   for (( m=0; m<=$(( ${#MACHINES[*]} -1 )); m++ )); do
+    
+    # Exclude failed machines
+    if [ "${MACHINES[$m]}" == "" ]; then
+      continue
+    fi
+    
+    # Prepare the launch
     ALLOWED=`dcosima-getinstances --remote=${MACHINES[$m]}`
     echo " "
     echo "Preparing for next launch:"
@@ -175,10 +199,11 @@ while [[ ${LAUNCHED} -lt ${INSTANCES} ]]; do
     if [[ ${ALLOWED} -gt 0 ]]; then
       LAUNCHED=$(( ${LAUNCHED} + 1 ))
       echo " * Launching instance ${LAUNCHED} on ${MACHINES[$m]}"
-      dcosima-runinstance --source=${SOURCE} --rundir=${LOCALDIR} --instanceid=${LAUNCHED} --remote=${MACHINES[$m]} --masterdir=${MASTERDIR} `if [[ ${ZIP} == TRUE ]]; then echo "--zip"; fi`
+      dcosima-runinstance --source=${SOURCE} --rundir=${LOCALDIR} --instanceid=${LAUNCHED} --remote=${MACHINES[$m]} `if [[ ${ZIP} == TRUE ]]; then echo "--zip"; fi`
       STARTED=1
     fi
     if [[ ${LAUNCHED} -eq ${INSTANCES} ]]; then break; fi
+      
   done
   
   if [[ ${STARTED} -eq 0 ]]; then
@@ -284,8 +309,21 @@ wait ${RSYNCPID}
 
 echo "All processes have finied and all data has been synced. Now deleting the remote data..."
 for (( m=0; m<=$(( ${#MACHINES[*]} -1 )); m++ )); do
-  echo " * Deleting ${MASTERDIR}/${LOCALDIR} on ${REMOTEHOST[$m]}"
-  ssh -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} "rm -rf ${MASTERDIR}/${LOCALDIR};"
+  echo " * Deleting ${REMOTEMASTERDIR}/${LOCALDIR} on ${REMOTEHOST[$m]}"
+
+  REMOTECOMMAND='COUNT=`grep -c ^directory ~/.dcosima.cfg`; if [ ${COUNT} -eq 1 ]; then grep ^directory ~/.dcosima.cfg; fi;'
+  REMOTEMASTERDIR=$(ssh -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} 'bash -s' <<< ${REMOTECOMMAND} )
+  if [ "$?" != "0" ]; then
+    echo "ERROR: Failed to read remote master directory"
+    continue
+  fi
+  REMOTEMASTERDIR=`echo ${REMOTEMASTERDIR} | awk '{ print $2 }'`
+  if [ "${REMOTEMASTERDIR}" == "" ]; then
+    echo "ERROR: No remote master directory -- cannot delete anything!"
+    continue
+  fi
+ 
+  ssh -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} "rm -rf ${REMOTEMASTERDIR}/${LOCALDIR};"
 done
 
 echo " " 
diff --git a/bin/dcosima-clean b/bin/dcosima-clean
--- a/bin/dcosima-clean
+++ b/bin/dcosima-clean
@@ -40,20 +40,6 @@ done
 CFG=~/.dcosima.cfg
 MEGALIBPATH="Science/Software"
 
-# Find the master simulation directory
-MASTERDIR=( `cat ${CFG} | grep "^directory" | gawk '{ print $2 }'` )
-if [[ "${MASTERDIR}" == "" ]]; then
-  MASTERDIR="dcosima"
-fi
-if [[ ${MASTERDIR} == /* ]]; then
-  echo "ERROR: The simulation directory can not be an absolute path! Using default path dcosima"
-  MASTERDIR="dcosima"
-fi
-if [[ ${MASTERDIR} == .* ]]; then
-  echo "ERROR: The simulation directory must sit in the users main directory! Using default path dcosima"
-  MASTERDIR="dcosima"
-fi
-
 # Read configuration file and extract machines
 MACHINES=( `cat ${CFG} | grep "^machine" | gawk '{ print $2 }'` )
 REMOTEUSER=( )
@@ -71,8 +57,20 @@ done
 
 # Create the install paths on all machines
 for (( m=0; m<=$(( ${#MACHINES[*]} -1 )); m++ )); do
-  echo "Cleaning ${MASTERDIR} on ${REMOTEUSER[$m]}@${REMOTEHOST[$m]}..."
-  ssh -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} "if [[ -d ${MASTERDIR} ]]; then rm -rf ${MASTERDIR}/Run_ID*; fi; exit 0;"
+  REMOTECOMMAND='COUNT=`grep -c ^directory ~/.dcosima.cfg`; if [ ${COUNT} -eq 1 ]; then grep ^directory ~/.dcosima.cfg; fi;'
+  REMOTEMASTERDIR=$(ssh -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} 'bash -s' <<< ${REMOTECOMMAND} )
+  if [ "$?" != "0" ]; then
+    echo "ERROR: Failed to read remote master directory"
+    continue
+  fi
+  REMOTEMASTERDIR=`echo ${REMOTEMASTERDIR} | awk '{ print $2 }'`
+  if [ "${REMOTEMASTERDIR}" == "" ]; then
+    echo "ERROR: Failed to read remote master directory"
+    continue
+  fi
+ 
+  echo "Cleaning ${REMOTEMASTERDIR} on ${REMOTEUSER[$m]}@${REMOTEHOST[$m]}..."
+  ssh -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} "if [[ -d ${REMOTEMASTERDIR} ]]; then rm -rf ${REMOTEMASTERDIR}/*_ID*; fi; exit 0;"
 done
 
 
diff --git a/bin/dcosima-runinstance b/bin/dcosima-runinstance
--- a/bin/dcosima-runinstance
+++ b/bin/dcosima-runinstance
@@ -16,7 +16,6 @@ commandhelp() {
   echo ""
   echo "Options:"
   echo "  --source=[file name]: The cosima source file name"
-  echo "  --masterdir=[directory name]: In which directory to store the data"
   echo "  --rundir=[directory name]: Unique directory where to store the files"
   echo "  --instanceid=[number]: ID of this run instance"
   echo "  --rsynccfg=[file name]: Fil;e where to store the rsync parameters"
@@ -54,7 +53,6 @@ REMOTEPORT=""
 SOURCE=""
 RUNDIR=""
 INSTANCEID=""
-MASTERDIR=""
 ZIP="FALSE"
 CFG="~/.dcosima.cfg"
 
@@ -70,9 +68,6 @@ for C in "${CMD[@]}"; do
     RUNDIR=`echo ${C} | awk -F"=" '{ print $2 }'` 
   elif [[ ${C} == *-i*=* ]]; then
     INSTANCEID=`echo ${C} | awk -F"=" '{ print $2 }'` 
-  elif [[ ${C} == *-m*=* ]]; then
-    MASTERDIR=`echo ${C} | awk -F"=" '{ print $2 }'`
-    eval MASTERDIR=${MASTERDIR}
   elif [[ ${C} == *-z* ]]; then
     ZIP="TRUE"
   elif [[ ${C} == *-h* ]]; then
@@ -124,14 +119,6 @@ if [ "${INSTANCEID}" == "" ]; then
 fi
 
 
-if [ "${MASTERDIR}" == "" ]; then
-  echo " "
-  echo "ERROR: You need to give a directory"
-  exit 1
-fi
-echo " * Directory: ${DIRECTORY}"
-
-
 eval CFG=${CFG}
 if [[ -f ${CFG} ]]; then
   echo " * Configuration file: ${CFG}"
@@ -152,13 +139,15 @@ echo "* Checking for remote global directory..."
 REMOTECOMMAND='COUNT=`grep -c ^directory ~/.dcosima.cfg`; if [ ${COUNT} -eq 1 ]; then grep ^directory ~/.dcosima.cfg; fi;'
 MASTERDIR=$(ssh -p ${REMOTEPORT} ${REMOTEUSER}@${REMOTEHOST} 'bash -s' <<< ${REMOTECOMMAND} )
 if [ "$?" != "0" ]; then
-  echo "ERROR: Failed to read remote global directory"
+  echo "ERROR: Failed to read the remote master directory to store the simulations"
+  echo "       Make sure you have a directory in the remote .dcosima.cfg file"
   exit 1
 fi
-if [ "${MASTERDIR}" != "" ]; then
-  MASTERDIR=`echo ${MASTERDIR} | awk '{ print $2 }'`
-else 
-  MASTERDIR="dcosima"
+MASTERDIR=`echo ${MASTERDIR} | awk '{ print $2 }'`
+if [ "${MASTERDIR}" == "" ]; then
+  echo "ERROR: Failed to read the remote master directory to store the simulations"
+  echo "       Make sure you have a directory in the remote .dcosima.cfg file"
+  exit 1
 fi
 echo "  --> Master directory: ${MASTERDIR}"
 
