CHG: Many more sanity checks and bug fixes

diff --git a/bin/dcosima b/bin/dcosima
--- a/bin/dcosima
+++ b/bin/dcosima
@@ -150,7 +150,6 @@ while [[ ${LAUNCHED} -lt ${INSTANCES} ]]; do
       REMOTEUSER[$m]=`echo "${MACHINES[$m]}" | awk -F"@" '{ print $1 }'` 
       REMOTEHOST[$m]=`echo "${MACHINES[$m]}" | awk -F"@" '{ print $2 }'  | awk -F":" '{ print $1 }'` 
       REMOTEPORT[$m]=`echo "${MACHINES[$m]}" | awk -F":" '{ print $2 }'`
-      echo " * Found remote machine: ${MACHINES[$m]} (user: ${REMOTEUSER[$m]}, address: ${REMOTEHOST[$m]}, port: ${REMOTEPORT[$m]})"
     done
     CFGMD5=`md5sum ${CFG}`
   fi
@@ -158,23 +157,51 @@ while [[ ${LAUNCHED} -lt ${INSTANCES} ]]; do
   # Verify the machines:
   AVAILABLEMACHINES=0
   for (( m=0; m<=$(( ${#MACHINES[*]} -1 )); m++ )); do
+  
+    # Do a quick test if the machine is availble:
+    REMOTENAME=`ssh -q -o ConnectTimeout=5 -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} "hostname"`
+    if [ "$?" != "0" ]; then
+      echo " * Remote machine: ${MACHINES[$m]} (user: ${REMOTEUSER[$m]}, address: ${REMOTEHOST[$m]}, port: ${REMOTEPORT[$m]}): NOT ACCESSIBLE"
+      MACHINES[$m]=""
+      continue
+    fi  
+      
+    # Check that cosima is installed
+    AVAILABLE=`ssh -q -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} ". .bash_local; type cosima > /dev/null" 2>&1`
+    if [ "${AVAILABLE}" != "" ]; then
+      echo " * Remote machine: ${MACHINES[$m]} (user: ${REMOTEUSER[$m]}, address: ${REMOTEHOST[$m]}, port: ${REMOTEPORT[$m]}): Cosima not found!"
+      MACHINES[$m]=""
+      continue
+    fi
+ 
+    # Check if we have a configuration file
+    CONFIGFILE=`ssh -q -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} "if [[ ! -f ~/.dcosima.cfg ]]; then echo "NO"; else echo "YES"; fi;"`
+    if [ "$?" != "0" ] || [ ${CONFIGFILE} != "YES" ]; then
+      echo " * Remote machine: ${MACHINES[$m]} (user: ${REMOTEUSER[$m]}, address: ${REMOTEHOST[$m]}, port: ${REMOTEPORT[$m]}): No dcosima configuration file found! Add one with at least the keywords instances and directory!"
+      MACHINES[$m]=""
+      continue
+    fi
+  
+    # Check if we have a master directory
     REMOTECOMMAND='COUNT=`grep -c ^directory ~/.dcosima.cfg`; if [ ${COUNT} -eq 1 ]; then grep ^directory ~/.dcosima.cfg; fi;'
     REMOTEMASTERDIR=$(ssh -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} 'bash -s' <<< ${REMOTECOMMAND} )
     if [ "$?" != "0" ]; then
-      echo " "
-      echo "ERROR: Failed to read remote master directory on ${MACHINES[$m]} --- excluding remote machine"
+      echo " * Remote machine: ${MACHINES[$m]} (user: ${REMOTEUSER[$m]}, address: ${REMOTEHOST[$m]}, port: ${REMOTEPORT[$m]}): Failed to read master directory!"
       MACHINES[$m]=""
       continue
     fi
     REMOTEMASTERDIR=`echo ${REMOTEMASTERDIR} | awk '{ print $2 }'`
     if [ "${REMOTEMASTERDIR}" == "" ]; then
-      echo " "
-      echo "ERROR: No remote master directory on ${MACHINES[$m]} --- excluding remote machine"
+      echo " * Remote machine: ${MACHINES[$m]} (user: ${REMOTEUSER[$m]}, address: ${REMOTEHOST[$m]}, port: ${REMOTEPORT[$m]}): Failed to read master directory!"
       MACHINES[$m]=""
       continue
     fi
+    
+    echo " * Found remote machine: ${REMOTENAME} (user: ${REMOTEUSER}, address: ${REMOTEHOST}, port: ${REMOTEPORT})"  
     AVAILABLEMACHINES=$(( ${AVAILABLEMACHINES} + 1 ))
+    
   done
+  
   # If we have NO machines available, we quit...
   if [ ${AVAILABLEMACHINES} -eq 0 ]; then
     echo " "
@@ -205,6 +232,7 @@ while [[ ${LAUNCHED} -lt ${INSTANCES} ]]; do
     if [[ ${LAUNCHED} -eq ${INSTANCES} ]]; then break; fi
       
   done
+  
   
   if [[ ${STARTED} -eq 0 ]]; then
     echo ""
diff --git a/bin/dcosima-listallinstances b/bin/dcosima-listallinstances
--- a/bin/dcosima-listallinstances
+++ b/bin/dcosima-listallinstances
@@ -59,14 +59,35 @@ echo "Available instances:"
 ALLALLOWED="0"
 ALLPOSSIBLE="0"
 for (( m=0; m<=$(( ${#MACHINES[*]} -1 )); m++ )); do
-  ALLOWED=`ssh -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} ". .bash_local; dcosima-getinstances"`
+  
+  # Do a quick test if the machine is available:
+  REMOTENAME=`ssh -q -o ConnectTimeout=5 -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} "hostname"`
+  if [ "$?" != "0" ]; then
+    echo " * Machine ${REMOTEHOST[$m]}, port ${REMOTEPORT[$m]}, user ${REMOTEUSER}: NOT ACCESSIBLE"
+    continue
+  fi  
+
+  # Check if cosima is installed
+  AVAILABLE=`ssh -q -o ConnectTimeout=5 -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} ". .bash_local; type cosima > /dev/null" 2>&1`
+  if [ "${AVAILABLE}" != "" ]; then
+    echo " * Machine ${REMOTEHOST[$m]}, port ${REMOTEPORT[$m]}, user ${REMOTEUSER}: Cosmia not installed"
+    continue
+  fi
+
+  # Check how many instances are allowed
+  ALLOWED=`ssh -q -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} ". .bash_local; dcosima-getinstances"`
+  if [ "$?" != "0" ]; then
+    echo " * Machine ${REMOTEHOST[$m]}, port ${REMOTEPORT[$m]}, user ${REMOTEUSER}: NOT ACCESSIBLE"
+    continue
+  fi  
   ALLALLOWED=$(( ${ALLALLOWED} + ${ALLOWED} ))
   
+  # Check how many instances are possible
   REMOTECOMMAND='COUNT=`grep -c ^instances ~/.dcosima.cfg`; if [ ${COUNT} -eq 1 ]; then grep ^instances ~/.dcosima.cfg; fi;'
   POSSIBLE=$(ssh -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} 'bash -s' <<< ${REMOTECOMMAND})
   if [ "$?" != "0" ]; then
-    echo "ERROR: Failed to read remote instances"
-    exit 1
+    echo " * Machine ${REMOTEHOST[$m]}, port ${REMOTEPORT[$m]}, user ${REMOTEUSER}: Failed to read instances"
+    continue
   fi
   if [ "${POSSIBLE}" != "" ]; then
     POSSIBLE=`echo ${POSSIBLE} | awk '{ print $2 }'`
@@ -79,7 +100,7 @@ for (( m=0; m<=$(( ${#MACHINES[*]} -1 )); m++ )); do
   fi
   ALLPOSSIBLE=$(( ${ALLPOSSIBLE} + ${POSSIBLE} ))
   
-  echo " * On machine ${REMOTEHOST[$m]}, port ${REMOTEPORT[$m]}, user ${REMOTEUSER}: ${ALLOWED} / ${POSSIBLE}"
+  echo " * Machine ${REMOTEHOST[$m]}, port ${REMOTEPORT[$m]}, user ${REMOTEUSER}: ${ALLOWED} / ${POSSIBLE}"
 done
 echo " "
 echo "Total number of instances: ${ALLALLOWED} / ${ALLPOSSIBLE}"
diff --git a/bin/dcosima-runinstance b/bin/dcosima-runinstance
--- a/bin/dcosima-runinstance
+++ b/bin/dcosima-runinstance
@@ -130,8 +130,41 @@ else
 fi
 echo " "
 
-echo "Preparing for launch:"
+
+
+echo "Preparing for launch ${INSTANCEID}:"
 echo " " 
+
+
+# Check if the host is available:
+echo "* Checking if host is available..."
+REMOTECOMMAND='hostname'
+HOST=$(ssh -p ${REMOTEPORT} ${REMOTEUSER}@${REMOTEHOST} 'bash -s' <<< ${REMOTECOMMAND} )
+if [ "$?" != "0" ]; then
+  echo "ERROR: Failed to access the host"
+  exit 1
+fi
+echo "  --> Host ${HOST} is accessible"
+
+
+# Check if cosima is available:
+echo "* Checking if host has cosima installed..."
+AVAILABLE=`ssh -q -p ${REMOTEPORT} ${REMOTEUSER}@${REMOTEHOST} ". .bash_local; type cosima > /dev/null" 2>&1`
+if [ "${AVAILABLE}" != "" ]; then
+  echo "ERROR: Cosima not found!"
+  exit 1
+fi
+echo "  --> Cosima found on machine"
+
+
+# Check if we have a configuration file
+echo "* Checking if host has a dcosima configuration file"
+CONFIGFILE=`ssh -q -p ${REMOTEPORT} ${REMOTEUSER}@${REMOTEHOST} "if [[ ! -f ~/.dcosima.cfg ]]; then exit 1; fi; exit 0;"`
+if [ "$?" != "0" ]; then
+  echo "ERROR: dcosima configuration file not found"
+  exit 1
+fi
+echo "  --> Cosima configuration file found"
 
 
 # Check if we have a global directory defined in the configuration file, if yes we will use that one
