CHG: Only clean a specific run not everything

diff --git a/bin/dcosima-clean b/bin/dcosima-clean
--- a/bin/dcosima-clean
+++ b/bin/dcosima-clean
@@ -15,6 +15,8 @@ commandhelp() {
   echo "Usage: dcosima-clean [options]";
   echo ""
   echo "Options:"
+  echo "  --directory=[run name]: Removes the directories of a specific run. "
+  echo "                          Used dcosima-showdiskspace to see all runs with not cleaned directories"
   echo "  --help: Show this help."
   echo ""
   echo "";
@@ -38,7 +40,30 @@ done
 
 # Default options:
 CFG=~/.dcosima.cfg
+REMOTEDIR="DCOSIMA_!!!!_IDONOTEXIST"
 MEGALIBPATH="Science/Software"
+
+# Overwrite default options with user options:
+for C in "${CMD[@]}"; do
+  if [[ ${C} == *-d*=* ]]; then
+    REMOTEDIR=`echo ${C} | awk -F"=" '{ print $2 }'`
+  elif [[ ${C} == *-h* ]]; then
+    echo ""
+    commandhelp
+    exit 0
+  else
+    echo ""
+    echo "ERROR: Unknown command line option: ${C}"
+    echo "       See \"dcosima-clean --help\" for a list of options"
+    exit 1
+  fi
+done
+
+if [[ ${REMOTEDIR} == "DCOSIMA_!!!!_IDONOTEXIST" ]]; then
+  echo "ERROR: You need to give a dcosima run directory"
+  exit 1
+fi
+
 
 # Read configuration file and extract machines
 MACHINES=( `cat ${CFG} | grep "^machine" | gawk '{ print $2 }'` )
@@ -46,16 +71,18 @@ REMOTEUSER=( )
 REMOTEHOST=( )
 REMOTEPORT=( )
 
-echo " "
-echo "Remote machines setup:"
+#echo " "
+#echo "Remote machines setup:"
 for (( m=0; m<=$(( ${#MACHINES[*]} -1 )); m++ )); do
   REMOTEUSER[$m]=`echo "${MACHINES[$m]}" | awk -F"@" '{ print $1 }'` 
   REMOTEHOST[$m]=`echo "${MACHINES[$m]}" | awk -F"@" '{ print $2 }'  | awk -F":" '{ print $1 }'` 
   REMOTEPORT[$m]=`echo "${MACHINES[$m]}" | awk -F":" '{ print $2 }'`
-  echo " * Found remote machine: ${MACHINES[$m]} (user: ${REMOTEUSER[$m]}, address: ${REMOTEHOST[$m]}, port: ${REMOTEPORT[$m]})"
+  #echo " * Found remote machine: ${MACHINES[$m]} (user: ${REMOTEUSER[$m]}, address: ${REMOTEHOST[$m]}, port: ${REMOTEPORT[$m]})"
 done
 
-# Create the install paths on all machines
+# Start with cleaning
+echo " "
+echo "Cleaning..."
 for (( m=0; m<=$(( ${#MACHINES[*]} -1 )); m++ )); do
   REMOTECOMMAND='COUNT=`grep -c ^directory ~/.dcosima.cfg`; if [ ${COUNT} -eq 1 ]; then grep ^directory ~/.dcosima.cfg; fi;'
   REMOTEMASTERDIR=$(ssh -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} 'bash -s' <<< ${REMOTECOMMAND} )
@@ -69,9 +96,34 @@ for (( m=0; m<=$(( ${#MACHINES[*]} -1 )); m++ )); do
     continue
   fi
  
-  echo "Cleaning ${REMOTEMASTERDIR} on ${REMOTEUSER[$m]}@${REMOTEHOST[$m]}..."
-  ssh -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} "if [[ -d ${REMOTEMASTERDIR} ]]; then rm -rf ${REMOTEMASTERDIR}/*_ID*; fi; exit 0;"
+  
+  # Let's first retrieve a list of all directories
+  REMOTECOMMAND='cd $(grep ^directory ~/.dcosima.cfg | tr -s " " | cut -d " " -f2); ls -dtr */;'
+  DIRECTORIES=$(ssh -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} 'bash -s' <<< ${REMOTECOMMAND} )
+  if [ "$?" != "0" ]; then
+    echo "ERROR: Unable to retrieve the directories!"
+    continue
+  fi
+  
+  # Check if the one we want exits and conforms to our standard (BlaBla_IDXXXXX)
+  CLEANED="NO"
+  for D in ${DIRECTORIES}; do
+    D=${D%%/}
+    if [[ ${D} == *_ID* ]] && [[ ${D} == ${REMOTEDIR} ]]; then
+      # If yes we remove it
+      echo " * Cleaning ${REMOTEMASTERDIR}/${D} on ${REMOTEUSER[$m]}@${REMOTEHOST[$m]}..."
+      ssh -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} "if [[ -d ${REMOTEMASTERDIR} ]]; then rm -rf ${REMOTEMASTERDIR}/${D}; fi; exit 0;"
+      CLEANED="YES"
+      break
+    fi
+  done
+  
+  if [[ ${CLEANED} == NO ]]; then
+    echo " * Nothing to clean on ${REMOTEUSER[$m]}@${REMOTEHOST[$m]}..."  
+  fi
+  
 done
 
+echo " "
 
 exit 0
