CHG: Updated dmegalib tools include now setup script

diff --git a/bin/dmegalib-checkaccessibility b/bin/dmegalib-checkaccessibility
--- a/bin/dmegalib-checkaccessibility
+++ b/bin/dmegalib-checkaccessibility
@@ -57,6 +57,11 @@ fi
 
 # Read configuration file and extract machines
 CFG=~/.dcosima.cfg
+if [ ! -f ${CFG} ]; then
+  echo "ERROR: No dmegalib configuration file present. Please run dmegalib-setup first."
+  exit 1
+fi
+
 MACHINES=( `cat ${CFG} | grep "^machine" | gawk '{ print $2 }'` )
 REMOTEUSER=( )
 REMOTEHOST=( )
diff --git a/bin/dmegalib-checkmegalib b/bin/dmegalib-checkmegalib
--- a/bin/dmegalib-checkmegalib
+++ b/bin/dmegalib-checkmegalib
@@ -25,6 +25,7 @@ commandhelp() {
 # Store command line as array
 CMD=( "$@" )
 
+
 # Check for help
 for C in "${CMD[@]}"; do
   if [[ ${C} == *-h* ]]; then
@@ -34,8 +35,14 @@ for C in "${CMD[@]}"; do
   fi
 done
 
+
 # Default options:
 CFG=~/.dcosima.cfg
+if [ ! -f ${CFG} ]; then
+  echo "ERROR: No dmegalib configuration file present. Please run dmegalib-setup first."
+  exit 1
+fi
+
 
 # Read configuration file and extract machines
 MACHINES=( `cat ${CFG} | grep "^machine" | gawk '{ print $2 }'` )
diff --git a/bin/dmegalib-listallinstances b/bin/dmegalib-listallinstances
--- a/bin/dmegalib-listallinstances
+++ b/bin/dmegalib-listallinstances
@@ -37,6 +37,10 @@ for C in "${CMD[@]}"; do
 done
 
 CFG=~/.dcosima.cfg
+if [ ! -f ${CFG} ]; then
+  echo "ERROR: No dmegalib configuration file present. Please run dmegalib-setup first."
+  exit 1
+fi
 
 # Read configuration file and extract machines
 MACHINES=( `cat ${CFG} | grep "^machine" | gawk '{ print $2 }'` )
diff --git a/bin/dmegalib-updatemegalib b/bin/dmegalib-updatemegalib
--- a/bin/dmegalib-updatemegalib
+++ b/bin/dmegalib-updatemegalib
@@ -15,7 +15,7 @@ commandhelp() {
   echo "Usage: dmegalib-updatemegalib [options]";
   echo ""
   echo "Options:"
-  echo "  --branch=name             : Use the given MEGAlib git branch (default it experimental)"
+  echo "  --branch=name             : Use the given MEGAlib git branch (default it master)"
   echo "  --machine=user@host:port  : Only update this machine, if not given use the ones in .dmegalib.cfg"
   echo "  --help                    : Show this help"
   echo ""
@@ -32,7 +32,7 @@ commandhelp() {
 # Store command line as array
 CMD=( "$@" )
 SINGLEMACHINE=""
-BRANCH="experimental"
+BRANCH="master"
 
 # Check for help
 for C in "${CMD[@]}"; do
@@ -49,6 +49,11 @@ done
 
 # Default options:
 CFG=~/.dcosima.cfg
+if [ ! -f ${CFG} ]; then
+  echo "ERROR: No dmegalib configuration file present. Please run dmegalib-setup first."
+  exit 1
+fi
+
 MEGALIBPATH="~/Science/Software" # Attention hard coded else where!
 
 # Read configuration file and extract machines
