CHG: Update to 2.24 head in cvs

diff --git a/bin/mcosima b/bin/mcosima
--- a/bin/mcosima
+++ b/bin/mcosima
@@ -23,11 +23,6 @@ help() {
 
 
 # Initialize
-#Cores=`grep cores /proc/cpuinfo | wc -l`
-#if [ ${Cores} -eq 0 ]; then Cores = 1; fi
-#Processors=`grep processor /proc/cpuinfo | wc -l`
-#Threads=`expr ${Cores} \* ${Processors}`;
-
 Threads=1;
 if ( `test -f /usr/sbin/sysctl` ); then
     Threads=`sysctl -n hw.logicalcpu_max`
@@ -52,7 +47,7 @@ fi
 if [ $# -eq 0 ] ; then
     echo " "
     echo "Error: You need to give at least a source file";
-    echo "       For details see mcosima -- help"
+    echo "       For details see mcosima --help"
     echo " "
     exit 0;
 fi;
@@ -68,7 +63,7 @@ while [ $# -gt 0 ] ; do
         if [ $# -eq 0 ]; then
             echo " "
             echo "Error: Options -p and -t need an argument";
-            echo "       For details see mcosima -- help"
+            echo "       For details see mcosima --help"
             echo " "
             exit 0;
         fi
@@ -81,7 +76,7 @@ while [ $# -gt 0 ] ; do
         if [ $# -eq 0 ]; then
             echo " "
             echo "Error: Option -n needs an argument";
-            echo "       For details see mcosima -- help"
+            echo "       For details see mcosima --help"
             echo " "
             exit 0;
         fi
@@ -98,7 +93,7 @@ while [ $# -gt 0 ] ; do
         else
             echo " "
             echo "Error: Only one source file allowed";
-            echo "       For details see mcosima -- help"
+            echo "       For details see mcosima --help"
             echo " "
             help; 
             exit 1;
@@ -111,7 +106,7 @@ done
 if [ "${Source}" == "!@#$" ]; then
     echo " "
     echo "Error: You need to give a source file";
-    echo "       For details see mcosima -- help"
+    echo "       For details see mcosima --help"
     echo " "
     exit 1;
 fi
@@ -122,7 +117,7 @@ then
 else
     echo " "
     echo "Error: The value behind parallel must be a number";
-    echo "       For details see mcosima -- help"
+    echo "       For details see mcosima --help"
     echo " "
     rm /tmp/aux
     exit 1;
@@ -142,12 +137,22 @@ ThreadsID="0"
 
 BaseNames=""
 while read line; do
-    Base=`echo $line | awk -F".FileName" '{ print $2 }'`; 
-    BaseNames="${BaseNames} ${Base}"
+    Base=`echo $line | awk -F ".FileName|.filename|.Filename" '{ print $2 }'`;
+    if [ "${Base}" != "" ]; then
+      BaseNames="${BaseNames} ${Base}"
+    fi
 done << EOF
-$(grep ".FileName" ${Source})
+$(grep -i ".FileName" ${Source})
 EOF
 # The above hack is necessary because "grep ".FileName" ${Source} | while read line; do" would launch a subprocess and BaseNames would not be set...
+
+if [ "${BaseNames}" == "" ]; then
+  echo " "
+  echo "Error: ${Source} does not contain a file name!"
+  echo " "
+  exit 1
+fi
+
 
 for Base in ${BaseNames}; do
     while true; do
@@ -169,7 +174,7 @@ for (( i=1; i <= ${Threads}; i+=1 )); do
     nohup nice -n ${Nice} cosima -v 0 -p ${ThreadsID} ${Source} > /dev/null &
     Pids="$Pids $! "
     if ( [ ${Threads} -gt 1 ] && [ $i -ne ${Threads} ] ); then
-        echo "Sleeping..."
+        echo "Sleeping ..."
         sleep 10
     fi
 done
@@ -177,21 +182,21 @@ done
 # Create a concatenation file
 
 # Extract the base file names from the source file
-grep ".FileName" ${Source} | while read line; do
-    Base=`echo $line | awk -F".FileName" '{ print $2 }'`; 
-    echo "Creating concatenation file for: ${Base}"
+grep -i ".FileName" ${Source} | while read line; do
+    Base=`echo $line | awk -F".FileName|.Filename|.filename" '{ print $2 }'`; 
+    echo "Creating concatenation file for simulation \"${Base}\""
     ConcatFileName="${Base}.p${ThreadsID}.sim" 
 
     # Wait until the first such file is created
     while ( test ! -f ${Base}.p${ThreadsID}.inc1.id1.sim ); do
         sleep 1
-        echo "Waiting for simulation file to appear..."
+        echo "Waiting for the simulation file \"${Base}.p${ThreadsID}.inc1.id1.sim\" to appear ..."
     done
 
     # Wait until the header is written
     while [ `wc -l ${Base}.p${ThreadsID}.inc1.id1.sim | awk -F" " '{ print $1 }'` -le 100 ]; do
         sleep 1;
-        echo "Waiting for first 100 lines to be written into the simulation file ${Base}.p${ThreadsID}.inc1.id1.sim..."
+        echo "Waiting for first 100 lines to be written into the simulation file \"${Base}.p${ThreadsID}.inc1.id1.sim\" ..."
     done
 
     # Extract the version information
@@ -215,7 +220,7 @@ grep ".FileName" ${Source} | while read line; do
     echo "EN" >> ${ConcatFileName}
     echo " " >> ${ConcatFileName}
 
-    echo "Created concatenation file ${ConcatFileName}"
+    echo "Created concatenation file \"${ConcatFileName}\""
 
     KillFileName="${Base}.p${ThreadsID}.killcosimas.bash"
     rm -f ${KillFileName}
