ADD: Option to give a parallel ID (useful for parallel simulations on big clusters)

diff --git a/bin/mcosima b/bin/mcosima
--- a/bin/mcosima
+++ b/bin/mcosima
@@ -36,6 +36,7 @@ help() {
   echo "    -m <threads>:  Maximum number of all threads (e.g. of all mcosima calls) on this machine"
   echo "    -n <nice>:     The nice level as an integer"
   #echo "    -d <seconds>:  Delay in seconds between starting jobs (min=default: 2 seconds)"
+  #echo "    -p:            use this parallel ID without checking for the cosima output files"
   echo "    -z:            zip the simulations files"
   echo "    -e:            Use the given special cosima executable instead"
   echo "    -w:            If set, wait until all jobs have finished."
@@ -58,6 +59,7 @@ elif [[ ${OSTYPE} == linux* ]]; then
 fi
 Source="!@#$";
 Max=${Threads}
+ParallelID=0
 Nice=0;
 Wait="no"
 Zip="no"
@@ -98,11 +100,11 @@ while [ $# -gt 0 ] ; do
     Found=1;
     Zip="yes"
     ;;
-  -p|-t)
+  -t)
     shift;
     if [ $# -eq 0 ]; then
       echo " "
-      echo "Error: Options -p and -t need an argument";
+      echo "Error: Option -t needs an argument";
       echo "       For details see mcosima --help"
       echo " "
       exit 0;
@@ -151,6 +153,19 @@ while [ $# -gt 0 ] ; do
     Nice=$1;
     #echo "Using nice level ${Nice}";
     ;;
+  -p)
+    shift;
+    if [ $# -eq 0 ]; then
+      echo " "
+      echo "Error: Option -p needs an argument";
+      echo "       For details see mcosima --help"
+      echo " "
+      exit 0;
+    fi
+    Found=1;
+    ParallelID=$1;
+    echo "Using nice level ${ParallelID}";
+    ;;
   -d)
     shift;
     if [ $# -eq 0 ]; then
@@ -162,7 +177,7 @@ while [ $# -gt 0 ] ; do
     fi
     Found=1;
     Delay=$1;
-    #echo "Using nice level ${Nice}";
+    #echo "Using nice level ${Delay}";
     ;;
   *)
     ;;
@@ -225,6 +240,18 @@ else
 fi
 if [ ${Delay} -le 2 ]; then Delay=2; fi
 
+if echo ${ParallelID} | grep "^[0-9]*$" > /tmp/aux
+then
+  rm /tmp/aux
+else
+  echo " "
+  echo "Error: The value behind parallel ID must be a number";
+  echo "       For details see mcosima --help"
+  echo " "
+  rm /tmp/aux
+  exit 1;
+fi
+
 if echo ${Max} | grep "^[0-9]*$" > /tmp/aux
 then
   rm /tmp/aux
@@ -253,13 +280,20 @@ echo "Executable: ${Executable}"
 echo "Number of threads to use: ${Threads}"
 echo "Maximum number of cosima threads on machine: ${Max}"
 echo "Source file: ${Source}"
+if [[ ${ParallelID} -gt 0 ]]; then
+  echo "Parallel ID: ${ParallelID}"
+fi
 echo "gzip'ing the output file: ${Zip}"
 echo "Waiting until all threads have finished: ${Wait}"
 
 
 
-# Search for the next unused sim file with ".pX.*sim" in it
+# Search for the next unused sim file with ".pX.*sim" in it or use the parallel ID
 ThreadsID="0"
+if [[ ${ParallelID} -gt 0 ]]; then
+  ThreadsID="${ParallelID}"
+fi
+
 
 BaseNames=""
 while read line; do
@@ -286,16 +320,18 @@ if [ "${BaseNames}" == "" ]; then
 fi
 
 
-for Base in ${BaseNames}; do
-  while true; do
-    ThreadsID=`expr ${ThreadsID} + 1`
-    N=`find . -name "${Base}.p${ThreadsID}.inc*.sim*" | wc -l | sed 's/ //g'`
-    #echo "Found: $N of ${Base}.p${ThreadsID}.*sim"
-    if [ "${N}" == "0" ]; then
-      break;
-    fi
+if [[ ${ParallelID} -eq 0 ]]; then
+  for Base in ${BaseNames}; do
+    while true; do
+      ThreadsID=`expr ${ThreadsID} + 1`
+      N=`find . -name "${Base}.p${ThreadsID}.inc*.sim*" | wc -l | sed 's/ //g'`
+      #echo "Found: $N of ${Base}.p${ThreadsID}.*sim"
+      if [ "${N}" == "0" ]; then
+        break;
+      fi
+    done
   done
-done
+fi
 
 echo " "
 
@@ -322,6 +358,9 @@ for (( i=1; i <= ${Threads}; i+=1 )); do
   Cmd="${ExecuteString} -v 0 -s ${Seed} -p ${ThreadsID} -f ${i} -t ${Tag}"
   if [[ "${Zip}" == "yes" ]]; then
     Cmd="${Cmd} -z"
+  fi
+  if [[ ${ParallelID} -gt 0 ]]; then
+    Cmd="${Cmd} -p ${ParallelID}"
   fi
   Cmd="${Cmd} ${Source}"
 
@@ -400,6 +439,7 @@ grep -i ".FileName" ${Source} | while read line; do
   fi
 
   # Create a concatenation file
+  rm -f ${ConcatFileName}
   echo "# Concatenation file generated by mcosima" >> ${ConcatFileName}
 
   if [[ "${Zip}" == "yes" ]]; then
