ADD: SphereWorld simulations and example

diff --git a/bin/mcosima b/bin/mcosima
--- a/bin/mcosima
+++ b/bin/mcosima
@@ -14,6 +14,7 @@ help() {
   echo "    -m <threads>:  Maximum number of all threads (e.g. of all mcosima calls) on this machine"
   echo "    -n <nice>:     The nice level as an integer"
   echo "    -z:            zip the simulations files"
+  echo "    -e:            Use the given special cosima executable instead" 
   echo "    -w:            If set, wait until all jobs have finished."
   echo "";
   echo "Example:";
@@ -37,15 +38,15 @@ Max=${Threads}
 Nice=0;
 Wait="no"
 Zip="no"
+Executable="cosima"
 
-# Check if cosima exists
-if (`test -f ${MEGAlib}/bin/cosima`); then
+# Check if executable exists
+if (`test -f ${MEGAlib}/bin/${Executable}`); then
   echo " "
-  echo "ERROR: The cosima executable does not exist. Try to (re-)compile MEGAlib."
+  echo "ERROR: The program ${Executable} does not exist. Try to (re-)compile the program"
   echo " "
   exit 1;
 fi
-
 
 
 # Verify the input:
@@ -97,6 +98,19 @@ while [ $# -gt 0 ] ; do
     Found=1;
     Max=$1;
     #echo "Using ${Threads} threads";
+    ;;
+  -e)
+    shift;
+    if [ $# -eq 0 ]; then
+      echo " "
+      echo "Error: Options -e needs an argument";
+      echo "       For details see mcosima --help"
+      echo " "
+      exit 0;
+    fi
+    Found=1;
+    Executable=$1;
+    echo "Using executable ${Executable}";
     ;;
   -n)
     shift;
@@ -171,10 +185,19 @@ else
   exit 1;
 fi
 
+# Check if cosima exists
+if (`test -f ${MEGAlib}/bin/${Executable}`); then
+  echo " "
+  echo "ERROR: The ${Executable} executable does not exist. Try to (re-)compile MEGAlib."
+  echo " "
+  exit 1;
+fi
+
 
 echo " "
 echo "Launching mcosima"
 echo " "
+echo "Executable: ${Executable}"
 echo "Number of threads to use: ${Threads}" 
 echo "Maximum number of cosima threads on machine: ${Max}" 
 echo "Source file: ${Source}" 
@@ -221,10 +244,10 @@ echo " "
 # Start the sims
 Pids=( )
 for (( i=1; i <= ${Threads}; i+=1 )); do
-  mdelay cosima ${Max}
+  mdelay ${Executable} ${Max}
   echo "Launching number ${i}/${Threads}"
   Random=`od -vAn -N4 -tu4 < /dev/urandom`
-  Cmd="nice -n ${Nice} cosima -v 0 -s ${Random} -p ${ThreadsID}"
+  Cmd="nice -n ${Nice} ${Executable} -v 0 -s ${Random} -p ${ThreadsID}"
   if [[ "${Zip}" == "yes" ]]; then
     Cmd="${Cmd} -z"
   fi
