ADD: Test if cosima is executable

diff --git a/bin/mcosima b/bin/mcosima
--- a/bin/mcosima
+++ b/bin/mcosima
@@ -81,7 +81,18 @@ if (`test -f ${MEGAlib}/bin/${Executable}`); then
   echo " "
   exit 1;
 fi
-
+# Check if the executable is executable
+Output=$( ${Executable} --help 2>&1 )
+if [[ "$?" != "0" ]]; then
+  echo " "
+  echo "ERROR: Cannot execute ${Executable} successfully. Calling ${Executable} --help generated the following output:"
+  echo " "
+  echo "--- start ---"
+  echo "${Output}"
+  echo "--- end ---"
+  echo " "
+  exit 1;
+fi
 
 # Verify the input:
 
