BUG: Fixes from svn head

diff --git a/bin/mcosima b/bin/mcosima
--- a/bin/mcosima
+++ b/bin/mcosima
@@ -58,7 +58,6 @@ fi;
 
 while [ $# -gt 0 ] ; do
   Found=0;
-  echo $1
   case $1 in
   -h|--help) 
     help; 
@@ -130,6 +129,14 @@ if [ "${Source}" == "!@#$" ]; then
   echo " "
   echo "Error: You need to give a source file";
   echo "       For details see mcosima --help"
+  echo " "
+  exit 1;
+fi
+RUNS=`grep "^Run\ " ${Source} | wc -l`
+if [ "${RUNS}" != "1" ]; then
+  echo " "
+  echo "Error: You have more than one run in the source file:"
+  grep "^Run\ " ${Source}
   echo " "
   exit 1;
 fi
