CHG: Join responses at the end

diff --git a/bin/mresponsecreator b/bin/mresponsecreator
--- a/bin/mresponsecreator
+++ b/bin/mresponsecreator
@@ -3,14 +3,14 @@
 
 commandhelp() {
   echo ""
-  echo "presponsecreator - parallel responsecreator on the same machine";
+  echo "mresponsecreator - multi-instance responsecreator (parallel runs on the same machine)";
   echo "(C) by Andreas Zoglauer"
   echo "";
   echo "Usage:";
-  echo "    presponsecreator <identical to responsereator>";
+  echo "    mresponsecreator <identical to responsereator>";
   echo "";
   echo "Example:";
-  echo "    presponsecreator -g Max.geo.setup -f Response.p1.inc*.id1.sim -r Binned -m ib -c Max.revan.cfg -b Max.mimrec.cfg -z";
+  echo "    mresponsecreator -g Max.geo.setup -f Response.p1.inc*.id1.sim -r Binned -m ib -c Max.revan.cfg -b Max.mimrec.cfg -z";
   echo "";
   echo "This script launches multiple instances of responsecreator."
   echo "The number of instances is limited to the number of cores."
@@ -32,6 +32,13 @@ fi
 if (`test -f ${MEGAlib}/bin/responsecreator`); then
   echo " "
   echo "ERROR: The responsecreator executable does not exist. Try to (re-)compile MEGAlib."
+  echo " "
+  exit 1;
+fi
+# Check if responsemanipulator exists
+if (`test -f ${MEGAlib}/bin/responsemanipulator`); then
+  echo " "
+  echo "ERROR: The responsemanipulator executable does not exist. Try to (re-)compile MEGAlib."
   echo " "
   exit 1;
 fi
@@ -90,6 +97,14 @@ done
 echo "Waiting till all sub-processes have finished..."
 wait
 echo "Done"
+echo " "
+echo "Joining files..."
+echo " "
+
+responsemainpulator -j ${NAME}
+
+echo "Done"
+echo " "
 
 exit 0;
 
