CHG: Default max load is number threads + 3

diff --git a/bin/mwait b/bin/mwait
--- a/bin/mwait
+++ b/bin/mwait
@@ -10,8 +10,8 @@ commandhelp() {
   echo "    mwait [options]"
   echo ""
   echo "Options:"
-  echo "  --instances=[integer or \"cores\", \"threads\"]: Maximum number of instances or \"cores\"/\"threads\" for the number of available cores or threads"
-  echo "  --load=[integer or \"cores\", \"threads\"]: Maximum system load as integer or \"cores\"/\"threads\" for the number of available cores or threads"
+  echo "  --instances=[integer or \"cores\", \"threads\"]: Maximum number of instances or \"cores\"/\"threads\" for the number of available cores or threads (default: 1)"
+  echo "  --load=[integer or \"cores\", \"threads\"]: Maximum system load as integer or \"cores\"/\"threads\" for the number of available cores or threads (default: threads + 3)"
   echo "  --program=[name]: The main program to wait for"
   #echo "  --auxprogram=[name]: Other programs to wait for"
   echo "  --memory: Make sure we have enough free memory, if more than one instance is running"
@@ -79,9 +79,11 @@ elif [[ ${INSTANCES} =~ ^[0-9]+$ ]]; then
   MAXTHREADS=${INSTANCES}
 else
   echo ""
-  echo "ERROR: Unknown number of threads: ${INSTANCES}. Using 1."  
+  echo "ERROR: Unknown number of threads: ${INSTANCES}. Using ${MAXTHREADS}."  
 fi
-MAXLOAD=10000
+
+MAXLOAD=$(getconf _NPROCESSORS_ONLN)
+MAXLOAD=$(( MAXLOAD + 3 ))
 if [[ ${LOAD} == t* ]]; then 
   MAXLOAD=$(getconf _NPROCESSORS_ONLN)
 elif [[ ${LOAD} == c* ]]; then  
@@ -91,7 +93,13 @@ elif [[ ${LOAD} =~ ^[0-9]+$ ]]; then
   MAXLOAD=${LOAD}
 else
   echo ""
-  echo "ERROR: Unknown load: ${LOAD}. Using 10000."  
+  echo "ERROR: Unknown load: ${LOAD}. Using ${MAXLOAD}."  
+fi
+
+if [[ ${PROGRAM} == "" ]]; then
+  echo ""
+  echo "ERROR: No program given. Exiting."
+  exit 1
 fi
 
 
