CHG: Allow default cfitsio installation to be used instead of HEASoft provided

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -345,33 +345,18 @@ echo ""
 echo "(d) HEAsoft (optional)"
 echo ""
 
-HEAsoftFound=1
-
-if [[ ${LHEASOFT} != "" ]]; then
-  if ( [ -f ${LHEASOFT}/lib/libcfitsio.a ] || [ -f ${LHEASOFT}/lib/libcfitsio.so ] ); then 
-    echo "Found HEAsoft: ${LHEASOFT}";
-    HEAsoftFound=0
-  else
-    echo "HEAsoft directory found, but there is no libcfitsio.[so or dylib] library in ${LHEASOFT}/lib!"
-    HEAVersionedLib=`ls ${LHEASOFT}/lib/libcfitsio_*.*`
-    if ( [ "$HEAVersionedLib" != "" ] ); then
-      echo "However I found a libcfitsio with a version number: $HEAVersionedLib"
-      echo "If you want to use HEAsoft please make a link, e.g., on Linux in the directory of the library do:" 
-      echo "sudo ln -s libcfitsio_X.XX.so licfitsio.so"
-    fi
-    echo ""
-    echo "-> HEAsoft is only required if you want to read / write fits files.";
-    echo "   This is very rarely the case. Thus you might just ignore that message."
-    echo "   If you reinstall HEAsoft later, please re-run configure and recompile";
-    HEAsoftFound=1
-  fi
-else 
-  echo "HEAsoft installation not found!";
+FitsIOFound=1
+locate libcfitsio &> /dev/null
+if [[ "$?" == "0" ]]; then
+  echo "Found cfitsio";
+  FitsIOFound=0
+else
+  echo "cfitsio not found"
   echo ""
-  echo "-> HEAsoft is only required if you want to read / write fits files.";
+  echo "-> cfitsio is only required if you want to read / write fits files.";
   echo "   This is very rarely the case. Thus you might just ignore that message."
-  echo "   If you reinstall HEAsoft later, please re-run configure and recompile";
-  HEAsoftFound=1
+  echo "   If you reinstall cfitsio later, please re-run configure and recompile";
+  FitsIOFound=1
 fi
 
 
@@ -522,7 +507,7 @@ echo "# " >> config/Makefile.options
 echo "# Important: Don't modify this sections by yourself " >> config/Makefile.options
 echo " " >> config/Makefile.options
 echo "GEANT4INSTALLED  = ${Geant4Found}" >> config/Makefile.options
-echo "HEASOFTINSTALLED = ${HEAsoftFound}" >> config/Makefile.options
+echo "HEASOFTINSTALLED = ${FitsIOFound}" >> config/Makefile.options
 echo "MPIINSTALLED = ${MPIFound}" >> config/Makefile.options
 echo " " >> config/Makefile.options
 
