ADD: A few sanity checks

diff --git a/config/configure_geant4versiontest b/config/configure_geant4versiontest
--- a/config/configure_geant4versiontest
+++ b/config/configure_geant4versiontest
@@ -6,6 +6,22 @@
 # Please see the MEGAlib software license and documentation for more informations.
 
 
+# Initial sanity checks
+if [[ ${MEGALIB} == "" ]]; then
+  echo ""
+  echo "ERROR: MEGAlib environment variable not set."
+  echo ""
+  exit 1
+fi
+
+if [[ ! -f ${MEGALIB}/config/AllowedGeant4Versions.txt ]]; then
+  echo ""
+  echo "ERROR: File not found: \${MEGALIB}/config/AllowedGeant4Versions.txt"
+  echo ""
+  exit 1
+fi
+
+
 # Allowed versions
 VERSIONS=`cat ${MEGALIB}/config/AllowedGeant4Versions.txt` 
 Geant4VersionMin=`echo ${VERSIONS} | awk -F" " '{ print $1 }'`
diff --git a/config/configure_rootversiontest b/config/configure_rootversiontest
--- a/config/configure_rootversiontest
+++ b/config/configure_rootversiontest
@@ -7,6 +7,20 @@
 
 
 # Allowed versions
+if [[ ${MEGALIB} == "" ]]; then
+  echo ""
+  echo "ERROR: MEGAlib environment variable not set."
+  echo ""
+  exit 1
+fi
+
+if [[ ! -f ${MEGALIB}/config/AllowedROOTVersions.txt ]]; then
+  echo ""
+  echo "ERROR: File not found: \${MEGALIB}/config/AllowedROOTVersions.txt"
+  echo ""
+  exit 1
+fi
+
 VERSIONS=`cat ${MEGALIB}/config/AllowedROOTVersions.txt` 
 RootVersionMin=`echo ${VERSIONS} | awk -F" " '{ print $1 }'`
 RootVersionMax=`echo ${VERSIONS} | awk -F" " '{ print $NF }'`
